Spring:
  application:
    name: itoken-client
  boot:
    admin:
      client:
        url: http://localhost:8084
  cloud:
    config:
      uri: http://localhost:8888
      name: itoken-client
      lavel: master
      profile: dev
